### ISSUE TITLE
needs longer timeout onblur

### ISSUE THREAD

**Issue by CSTufts** [benedwards44/lwc-combobox-autocomplete#1]
Love this, works like a charm. small bug though...

your timeout in the onblur wasn't long enough (took me way too long to figure that one out)

I moved it to 500 instead of 100 and honestly you can't tell that theres any delay... 
I can create a PR if you want, but it's probably just easier for you to update it.

thanks for this though, it works great once I figured that out

**Comment by benedwards44** [comment]
Thanks @CSTufts, I've made the change.
